services:
  postgres:
    container_name: nest-clean-arch-pg
    image: bitnami/postgresql:17.0.0
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: nest-clean-arch
